#%RAML 1.0 Library
usage:
traits:
  transactionId: !include traits/headers-transactionId-trait.raml
  departureLocationCode: !include traits/queryParams-departureLocationCode-trait.raml
  destinationLocationCode: !include traits/queryParams-destinationLocationCode-trait.raml
types:
  commonError: !include dataType/common-error-dataType.raml
  